### PR TITLE
fix: compatible filters and show more button

### LINKED ISSUE #822: Filters for product families and tags are not compatible
So.... we've experienced that as long as you stick to only clicking on tags or famiies, everything works. But the moment a user selects a few families for example, and then moves to also selecting a tag... only the ones with the tag show up.

It might be a good idea to make them compatible - or at least de-select for the user the family tags if they are not compatible

### LINKED ISSUE #823: "Show more" button on tags and families is not working
We might have to either remove it or make it so that only 5-6 elements are shown (so that the show more button actually has an effect). Otherwise, as pointed out by @greschd, it's a bit useless

### PR DESCRIPTION
**Pull request by moe-ad**
closes #822, closes #823.

### CODE REVIEW

**Comment by moe-ad** [comment]
@jorge can you check this also locally on your side?

**Comment by RobPasMue** [comment]
I doubt it's @jorge - it should be @jorgepiloto

**Comment by moe-ad** [comment]
> I doubt it's @jorge - it should be @jorgepiloto

😆 thanks for catching that.

File: doc/source/_static/js/landing_page.js [hunk 1]
```diff
@@ -67,29 +70,39 @@ function displayFamilies(familyCounts) {
...
+  const showMoreButton = document.querySelector(".product-families .show-more");
+  showMoreButton.addEventListener("click", () => {
+    if (!showMoreClicked) {
+      document
+        .querySelectorAll(".family-row")
+        .forEach((row) => (row.style.display = "flex"));
+      showMoreButton.style.display = "none"; // Hide "Show more" after clicking
+      showMoreClicked = true;
+    }
+  });
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:89]: i dont see you are handling the show less here. Instead of handling the showless in another function, use the text context. 
```suggestion
  const showMoreButton = document.querySelector(".product-families .show-more");
  const rows = document.querySelectorAll(".family-row");
  showMoreButton.addEventListener("click", () => {
    if (showMoreClicked) {
      rows.forEach((row, index) => {
        if (index >= maxVisible) {
          row.style.display = "none";
        }
      });
      showMoreButton.textContent = "Show more";
      showMoreClicked = false;
    } else {
      rows.forEach((row) => {
        row.style.display = "flex";
      });
      showMoreButton.textContent = "Show less";
      showMoreClicked = true;
    }
  });
}
```

Comment (Revathyvenugopal162) [reply doc/source/_static/js/landing_page.js:89]: Screenshot 2025-02-05 at 08 59 32
Screenshot 2025-02-05 at 08 59 41

File: doc/source/_static/js/landing_page.js [hunk 2]
```diff
@@ -100,19 +113,34 @@ function displayTags(tagCounts) {
...
+  const showMoreButton = document.querySelector(".product-tags .show-more");
+  showMoreButton.addEventListener("click", () => {
+    if (!showMoreClicked) {
+      document
+        .querySelectorAll(".tag-row")
+        .forEach((row) => (row.style.display = "flex"));
+      showMoreButton.style.display = "none"; // Hide "Show more" after clicking
+      showMoreClicked = true;
+    }
+  });
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:132]: same here
```suggestion
  const showMoreButton = document.querySelector(".product-tags .show-more");
  const Tagrows = document.querySelectorAll(".tag-row");
  showMoreButton.addEventListener("click", () => {
    if (showMoreClicked) {
      Tagrows.forEach((row, index) => {
        if (index >= maxVisible) {
          row.style.display = "none";
        }
      });
      showMoreButton.textContent = "Show more";
      showMoreClicked = false;
    }
    else {
      Tagrows.forEach((row) => {
        row.style.display = "flex";
      });
      showMoreButton.textContent = "Show less";
      showMoreClicked = true;
    }
  });
```

File: doc/source/_static/js/landing_page.js (hunk 1 above)
Comment (moe-ad) [reply doc/source/_static/js/landing_page.js:89]: Thanks for the review and suggestion Revathy!
Very much appreciated.

File: doc/source/_static/js/landing_page.js [hunk 3]
```diff
@@ -67,29 +70,48 @@ function displayFamilies(familyCounts) {
...
     familyRow.appendChild(checkbox);
     familyRow.appendChild(familyName);
-    //familyRow.appendChild(familyCountElem);
 
     familiesContainer.appendChild(familyRow);
   });
+
+  // Handle "Show more" click
+  const showMoreButton = document.querySelector(".product-families .show-more");
+  const Familyrows = document.querySelectorAll(".family-row");
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:81]:
```suggestion
  const FamilyRows = document.querySelectorAll(".family-row");
```

File: doc/source/_static/js/landing_page.js [hunk 4]
```diff
@@ -67,29 +70,48 @@ function displayFamilies(familyCounts) {
...
+  showMoreButton.addEventListener("click", () => {
+    if (showMoreClicked) {
+      Familyrows.forEach((row, index) => {
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:84]:
```suggestion
      FamilyRows.forEach((row, index) => {
```

File: doc/source/_static/js/landing_page.js [hunk 5]
```diff
@@ -67,29 +70,48 @@ function displayFamilies(familyCounts) {
...
+        if (index >= maxVisible) {
+          row.style.display = "none";
+        }
+      });
+      showMoreButton.textContent = "Show more";
+      showMoreClicked = false;
+    } else {
+      Familyrows.forEach((row) => {
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:92]:
```suggestion
      FamilyRows.forEach((row) => {
```

File: doc/source/_static/js/landing_page.js [hunk 6]
```diff
@@ -100,19 +122,43 @@ function displayTags(tagCounts) {
...
 
     tagsContainer.appendChild(tagRow);
   });
+
+  // Handle "Show more" click
+  const showMoreButton = document.querySelector(".product-tags .show-more");
+  const Tagrows = document.querySelectorAll(".tag-row");
+  showMoreButton.addEventListener("click", () => {
+    if (showMoreClicked) {
+      Tagrows.forEach((row, index) => {
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:136]:
```suggestion
      TagRows.forEach((row, index) => {
```

File: doc/source/_static/js/landing_page.js [hunk 7]
```diff
@@ -100,19 +122,43 @@ function displayTags(tagCounts) {
...
+        if (index >= maxVisible) {
+          row.style.display = "none";
+        }
+      });
+      showMoreButton.textContent = "Show more";
+      showMoreClicked = false;
+    } else {
+      Tagrows.forEach((row) => {
```
Comment (Revathyvenugopal162) [inline doc/source/_static/js/landing_page.js:144]:
```suggestion
      TagRows.forEach((row) => {
```

File: doc/source/_static/js/landing_page.js [hunk 8]
```diff
@@ -100,19 +122,43 @@ function displayTags(tagCounts) {
...
     tagRow.appendChild(checkbox);
     tagRow.appendChild(tagName);
-    //tagRow.appendChild(tagCountElem);
 
     tagsContainer.appendChild(tagRow);
   });
+
+  // Handle "Show more" click
+  const showMoreButton = document.querySelector(".product-tags .show-more");
+  const Tagrows = document.querySelectorAll(".tag-row");
```
[the remark this answers is not in the document]
Comment (Revathyvenugopal162) [reply doc/source/_static/js/landing_page.js]: @moe-ad  Please test this locally. The variable with this name may already exist in the file. In that case, the script might fail to execute.( i can see a variable TagRow above)

**Review by Revathyvenugopal162 — COMMENTED** [review]
left some minor changes, LGTM

**Review by RobPasMue — APPROVED** [review]
